new approval-timeout action

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -15,7 +15,7 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4.1.7
       - name: Run condition check
-        uses: ./.github/actions/deployment
+        uses: ./.github/actions/condition-check
         with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
@@ -24,60 +24,68 @@ jobs:
     needs: check-condition
     if: ${{ needs.check-condition.outputs.RUN_DEPLOYMENT }} == 'true'
     steps:
-      - name: Wait for approval or timeout
-        run: |
-          ENVIRONMENT_NAME="production"
-          TIMEOUT_MINUTES=15
-          echo "Waiting $TIMEOUT_MINUTES minutes for approval ..."
+      - name: Run condition check
+        uses: ./.github/actions/approval-timeout
+        with:
+          ENVIRONMENT: production
+          TIMEOUT: 15
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_REPO: ${{ github.repository }}
+          GITHUB_RUN_ID: ${{ github.run_id }}
+      # - name: Wait for approval or timeout
+      #   run: |
+      #     ENVIRONMENT_NAME="production"
+      #     TIMEOUT_MINUTES=15
+      #     echo "Waiting $TIMEOUT_MINUTES minutes for approval ..."
 
-          # iterative checks every minute
-          for ((i=1; i<=$TIMEOUT_MINUTES; i++)); do
+      #     # iterative checks every minute
+      #     for ((i=1; i<=$TIMEOUT_MINUTES; i++)); do
 
-            if [[ $i -gt 1 ]]; then
-              MINUTE_STRING="minutes"
-            else
-              MINUTE_STRING="minute"
-            fi
+      #       if [[ $i -gt 1 ]]; then
+      #         MINUTE_STRING="minutes"
+      #       else
+      #         MINUTE_STRING="minute"
+      #       fi
 
-            sleep 60
-            echo "Checking status after $i $MINUTE_STRING ..."
+      #       sleep 60
+      #       echo "Checking status after $i $MINUTE_STRING ..."
 
-            DEPLOYMENT_RESPONSE=$(curl -s \
-              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-              -H "Accept: application/vnd.github.v3+json" \
-              "https://api.github.com/repos/${{ github.repository }}/deployments?environment=$ENVIRONMENT_NAME&per_page=1")
+      #       DEPLOYMENT_RESPONSE=$(curl -s \
+      #         -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+      #         -H "Accept: application/vnd.github.v3+json" \
+      #         "https://api.github.com/repos/${{ github.repository }}/deployments?environment=$ENVIRONMENT_NAME&per_page=1")
 
-            DEPLOYMENT_ID=$(echo "$DEPLOYMENT_RESPONSE" | jq -r '.[0].id')
-            STATUS_RESPONSE=$(curl -s \
-              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-              -H "Accept: application/vnd.github.v3+json" \
-              "https://api.github.com/repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses")
+      #       DEPLOYMENT_ID=$(echo "$DEPLOYMENT_RESPONSE" | jq -r '.[0].id')
+      #       STATUS_RESPONSE=$(curl -s \
+      #         -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+      #         -H "Accept: application/vnd.github.v3+json" \
+      #         "https://api.github.com/repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses")
 
-            STATUS=$(echo "$STATUS_RESPONSE" | jq -r '.[0].state')
-            if [[ ($STATUS == "error" || "$STATUS" == "waiting") && $i -lt $TIMEOUT_MINUTES ]]; then
-              echo "Approval not received yet - keep waiting for it"
-            else
-              break
-            fi
+      #       STATUS=$(echo "$STATUS_RESPONSE" | jq -r '.[0].state')
+      #       if [[ ($STATUS == "error" || "$STATUS" == "waiting") && $i -lt $TIMEOUT_MINUTES ]]; then
+      #         echo "Approval not received yet - keep waiting for it"
+      #       else
+      #         break
+      #       fi
 
-          done
+      #     done
 
-          # tags: error, failure, inactive, in_progress, queued, pending, success
-          echo "Current deployment status is '$STATUS'"
-          if [[ $STATUS != "error" && "$STATUS" != "waiting" ]]; then
-            echo "--> Approval received"
-            exit 0
-          else
-            echo "--> No approval found - cancelling workflow ..."
-            curl -L \
-              -X POST \
-              -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-              -H "X-GitHub-Api-Version: 2022-11-28" \
-              "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel"
-            echo "Workflow cancelled"
-            exit 1
-          fi
+      #     # tags: error, failure, inactive, in_progress, queued, pending, success
+      #     echo "Current deployment status is '$STATUS'"
+      #     if [[ $STATUS != "error" && "$STATUS" != "waiting" ]]; then
+      #       echo "--> Approval received"
+      #       exit 0
+      #     else
+      #       echo "--> No approval found - cancelling workflow ..."
+      #       curl -L \
+      #         -X POST \
+      #         -H "Accept: application/vnd.github+json" \
+      #         -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+      #         -H "X-GitHub-Api-Version: 2022-11-28" \
+      #         "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel"
+      #       echo "Workflow cancelled"
+      #       exit 1
+      #     fi
 
   deployment:
     runs-on: ubuntu-latest
@@ -150,13 +158,13 @@ jobs:
           curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh
           mkdir -p ~/.config/scw
           tee ~/.config/scw/config.yaml << EOF
-          access_key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
-          secret_key: ${{ secrets.SCALEWAY_SECRET_KEY }}
-          default_organization_id: ${{ secrets.SCALEWAY_ORGANIZATION_ID }}
-          default_project_id: ${{ secrets.SCALEWAY_PROJECT_ID }}
-          default_zone: ${{ secrets.SCALEWAY_ZONE }}
-          default_region: $REGION
-          api_url: https://api.scaleway.com
+            access_key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
+            secret_key: ${{ secrets.SCALEWAY_SECRET_KEY }}
+            default_organization_id: ${{ secrets.SCALEWAY_ORGANIZATION_ID }}
+            default_project_id: ${{ secrets.SCALEWAY_PROJECT_ID }}
+            default_zone: ${{ secrets.SCALEWAY_ZONE }}
+            default_region: $REGION
+            api_url: https://api.scaleway.com
           EOF
 
           # Delete previous DNS records
